name: flutter_penta_core
description: "A core package for flutter projects."
version: 0.0.3
homepage: https://github.com/ANILSRGT/flutter_penta_core
funding:
  - https://www.buymeacoffee.com/ANILSRGT

environment:
  sdk: "^3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.3.0
  flutter_lints: ^2.0.0

flutter:
