name: flutter_penta_core
description: "A core package for flutter projects."
version: 0.0.6
homepage: https://github.com/ANILSRGT/flutter_penta_core
funding:
  - https://www.buymeacoffee.com/ANILSRGT

environment:
  sdk: "^3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Used for BaseViewMVVMWithMobx. It is a base class for views.
  mobx: ^2.2.0

  # Used for string_extensions.dart
  easy_localization: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
